# Generated by Django 4.1 on 2022-09-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLavatres', '0002_alter_animal_fecha_turno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indumentaria',
            old_name='ropa_banca',
            new_name='ropa_blanca',
        ),
    ]
